name: todoapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter_riverpod: ^2.5.1
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  go_router: ^14.1.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  path: ^1.9.0
  sqflite: ^2.3.3+1

flutter:
  uses-material-design: true
